#!/usr/bin/env bash

### IMPORTANT!!!
### Keep this file in sync with action.yml

primerSpecFiles=$(grep -l "window\.PrimerSpecConfig" _site/**/*.html _site/*.html)

for file in $primerSpecFiles; do
  relativePath=${file#_site/}
  pdfFile="_site/assets/primer-spec-pdf/${relativePath%.html}.pdf"
  pdfFileDir=${pdfFile%/*}
  echo "Source: $file"
  echo "Dest: $pdfFile"
  echo ""
  mkdir -p $pdfFileDir
  chrome --headless --print-to-pdf="$pdfFile" $file
done